import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'welcome': 'Welcome to TM-News',
          'loginReg': 'Login : Singup',
          'skiplogin': 'Skip Login',
          'login': 'login',
          'singup': 'singup',
          'email': 'Email',
          'password': 'Password',
          'user_name': 'User Name',
          'error': 'Error',
          'login_slogan': 'Login and enjoy our services',
          'inp_name': 'Input your user name',
          'inp_email': 'Input your email',
          'inp_password': 'Input your password',
          'unhidepassword': 'Unhide password',
          'singup_slogan': 'Singup be one of us',
          'confirmation': 'Confirmation',
          'latestnews': 'Latest News',
          'general': 'General',
          'business': 'Business',
          'entertainment': 'Entertainment',
          'health': 'Health',
          'science': 'Science',
          'sports': 'Sports',
          'technology': 'Technology',
          'bookmark': 'bookmark',
          'readmore': 'Read more',
          'newspaper': 'Newspaper',
          'livesports': 'Live Sports Events',
          'currency': 'Currency',
          'currencyconverter': 'Currency Converter',
          'convert': 'Convert',
          'darkmode': 'Dark Mode',
          "applanguage": "App Language",
          "bookmarks": "Bookmarks",
          "usersettings": "User Settings",
          'logout': 'Logout',
          'searchbox': 'Search Box',
          'searchword': 'Search word',
          'searchnow': 'Search Now',
          'searchfeatures': 'Search features',
          'title': 'Title',
          'description': 'Description',
          'content': 'Content',
          'from': 'From',
          'to': 'To',
        },
        'ar': {
          'welcome': 'مرحباً في اخر الاخبار',
          'loginReg': 'دخول : تسجيل',
          'skiplogin': 'تخطي الدخول',
          'login': 'دخول',
          'singup': 'تسجيل',
          'email': 'البريد الالكتروني',
          'password': 'كلمة المرور',
          'user_name': 'اسم المستخدم',
          'error': 'خطأ',
          'login_slogan': 'سجل دخولك واستمتع معنا',
          'inp_name': 'ادخل اسمك',
          'inp_email': 'ادخل البريد الالكتروني',
          'inp_password': 'ادخل كلمة المرور',
          'unhidepassword': 'اظهار كلمة المرور',
          'singup_slogan': 'سجل و انضم إلينا',
          'confirmation': 'تأكيد كلمة المرور',
          'latestnews': 'اخر الاخبار',
          'general': 'عام',
          'business': 'اعمال',
          'entertainment': 'تسلية',
          'health': 'صحة',
          'science': 'علم',
          'sports': 'رياضة',
          'technology': 'تكنولوجيا',
          'bookmark': 'حفظ',
          'readmore': 'اكمل القراءة',
          'newspaper': 'الجريدة',
          'livesports': 'احداث رياضية مباشرة',
          'currency': 'العملة',
          'currencyconverter': 'محول العملات',
          'convert': 'تحويل',
          'darkmode': 'الوضع الداكن',
          "applanguage": "لغة التطبيق",
          "bookmarks": "المحفوظات",
          "usersettings": "اعدادت المستخدم",
          'logout': "خروج",
          'searchbox': 'صندوق البحث',
          'searchword': 'كلمة البحث',
          'searchnow': 'ابحث',
          'searchfeatures': 'ميزات البحث',
          'title': 'العنوان',
          'description': 'الوصف',
          'content': 'المحتوي',
          'from': 'من',
          'to': 'الي',
        }
      };
}
