// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWOfZJdl5Tx_0dZzS8Nd8WbXDKYNhBHE',
    appId: '1:373075424845:web:9a13e45676efa3d17e4e04',
    messagingSenderId: '373075424845',
    projectId: 'tell-me-news',
    authDomain: 'tell-me-news.firebaseapp.com',
    storageBucket: 'tell-me-news.appspot.com',
    measurementId: 'G-2515G7T3FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XWf8IKV_YzOrHubzzbaTnYq0TuHc7BY',
    appId: '1:373075424845:android:fbe57699ad2adab37e4e04',
    messagingSenderId: '373075424845',
    projectId: 'tell-me-news',
    storageBucket: 'tell-me-news.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcXsSR-GXV_nT4iz1txBZAeoyhVpZuDl4',
    appId: '1:373075424845:ios:cedf093e2747dc137e4e04',
    messagingSenderId: '373075424845',
    projectId: 'tell-me-news',
    storageBucket: 'tell-me-news.appspot.com',
    iosClientId: '373075424845-3k03uka1bqeke7omg6vrtvs8s72ul6nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tellMeNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcXsSR-GXV_nT4iz1txBZAeoyhVpZuDl4',
    appId: '1:373075424845:ios:cedf093e2747dc137e4e04',
    messagingSenderId: '373075424845',
    projectId: 'tell-me-news',
    storageBucket: 'tell-me-news.appspot.com',
    iosClientId: '373075424845-3k03uka1bqeke7omg6vrtvs8s72ul6nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tellMeNews',
  );
}
